#!/usr/bin/env bash

if [ -z "$1" ]; then
	echo "Missing argument (commit message). Did you try to run this manually?"
	exit 1
fi

commitTitle="$(cat $1 | head -n1)"

# ignore merge requests
if echo "$commitTitle" | grep -qE "^Merge branch \'"; then
	exit 0
fi

# check semantic versioning scheme
if ! echo "$commitTitle" | grep -qE '^(?:feat|fix|docs|style|refactor|perf|test|chore)\(?(?:[A-Za-z0-9_,-]+|\s|\-|_|,)?\)?:\s\w+'; then
	echo "Your commit title did not follow semantic versioning: $commitTitle"
	echo "Please see https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commit-message-format"
	exit 1
fi

if echo "$commitTitle" | grep -qE '^(?:\w+):'; then

  mods=$(echo $(git diff --cached --name-only | grep / | sed -e 's,/.*,,g' | sort -u) | sed -e 's/ /,/g')

  if [ "${mods}" = "" ]; then
    exit 0
  fi

  tmpfile=$(mktemp)

  echo "$commitTitle" | sed -e "s/:/\(${mods}\):/" > ${tmpfile}
  tail -n +2 $1 >> ${tmpfile}

  mv ${tmpfile} "$1"

  exit 0
fi

